server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Explicitly define 3D model types
    types {
        model/gltf-binary glb;
        model/gltf+json   gltf;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}